

USE DATABASE CS5542_DB;

CREATE OR REPLACE TABLE RAW.DOCS(
  DOC_ID STRING,
  TITLE STRING,
  SOURCE STRING,
  TEXT STRING,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE APP.CHUNKS (
  CHUNK_ID STRING,
  DOC_ID STRING,
  PAGE_NUM INT, 
  CHUNK_TEXT STRING
)