

SELECT SOURCE, COUNT(*) AS N_DOCS
FROM RAW.DOCS
GROUP BY SOURCE
ORDER BY N_DOCS DESC;

-- QUERY 2: FILTER  + TIME BASED
SELECT DATE_TRUNC('DAY', CREATED_AT) AS DAY, COUNT(*) AS N
FROM RAW.DOCS
WHERE CREATED_AT IS NOT NULL
GROUP BY DAY
ORDER BY DAY DESC;

-- QUERY 3: JOIN
SELECT d.SOURCE, COUNT(c.CHUNK_ID) AS N_CHUNKS
FROM RAW.DOCS d
JOIN APP.CHUNKS c ON d.DOC_ID = c.DOC_ID
GROUP BY d.SOURCE 
ORDER BY N_CHUNKS DESC;


-- CREATE A VIEW
CREATE OR REPLACE VIEW APP.V_APP_DATA AS
SELECT DOC_ID, TITLE, SOURCE, LEFT(TEXT, 500) AS PREVIEW
FROM RAW.DOCS;
